<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="malight">

  <xacro:property name="base_link_height" value="0.15" />
  <xacro:property name="wheel_radius" value="0.08" />
  <xacro:property name="wheel_length" value="0.05" />
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="laser_link" value="0.05" /> <!-- Size of square 'laser' box -->

  <xacro:macro name="box_inertial_matrix" params="mass w h d">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="${mass*((h*h)+(d*d))/12}" ixy="0.0" ixz="0.0" iyy="${mass*((w*w)+(d*d))/12}" iyz="0.0" izz="${mass*((w*w)+(h*h))/12}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertial_matrix" params="mass r h ">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="${mass*((3*r*r)+(h*h))/12.0}" ixy="0.0" ixz="0.0" iyy="${mass*((3*r*r)+(h*h))/12.0}" iyz="0.0" izz="${mass*r*r/12.0}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertial_matrix" params="mass r">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="${2*(mass*r*r)/5}" ixy="0.0" ixz="0.0" iyy="${2*(mass*r*r)/5}" iyz="0.0" izz="${2*(mass*r*r)/5}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="wheel" params="name z_offset l r mass">
    <link name="${name}">
      <visual>
      <origin xyz="0 0 ${z_offset}"/>
      <geometry>
        <cylinder length="${l}" radius="${r}" />
      </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${z_offset}"/>
        <geometry>
          <cylinder length="${l}" radius="${r}" />
        </geometry>
      </collision>
      <xacro:cylinder_inertial_matrix mass="${mass}" r="${r}" h="${l}"/>
    </link>
  </xacro:macro>



  <link name="base_link">
    <visual>
    <origin xyz="0 0 ${(base_link_height/2.0)+(wheel_radius-0.025)}"/>
    <geometry>
      <box size="0.5 0.3 ${base_link_height}" />
    </geometry>
    </visual>
    <collision>
     <origin xyz="0 0 ${(base_link_height/2.0)+(wheel_radius-0.025)}"/>
     <geometry>
       <box size="0.5 0.3 ${base_link_height}" />
     </geometry>
   </collision>
   <xacro:box_inertial_matrix mass="1.5" w="0.5" h="0.3" d="0.15" />
  
  </link>
  
  <xacro:wheel name="left_wheel" z_offset="${wheel_length/2.0}" l="${wheel_length}" r="${wheel_radius}" mass="0.6" />

  <xacro:wheel name="right_wheel" z_offset="${wheel_length/2.0}" l="${wheel_length}" r="${wheel_radius}" mass="0.6" />

  <link name="caster_wheel">
      <visual>
      <origin xyz="0 0 0 "/>
      <geometry>
        <sphere radius="${ (((base_link_height/2.0)+(wheel_radius-0.025))/4)-0.005 }" />
      </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0"/>
        <geometry>
          <sphere radius="${ (((base_link_height/2.0)+(wheel_radius-0.025))/4)-0.005}" />
        </geometry>
        <surface>
          <friction>
            <ode>
              <mu>0.03</mu>
              <mu2>0.03</mu2>
            </ode>
          </friction>
        </surface>
      </collision>
      <!--<xacro:sphere_inertial_matrix mass="0.3" r="${ (((base_link_height/2.0)+(wheel_radius-0.025))/4)-0.005}"/> -->
  </link>

  <!-- Camera -->
  <link name="camera_link">
    <collision>
      <geometry>
      <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
      <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <!-- Laser -->
  <link name='laser_link'>
      <collision>
      		<geometry>
        		<box size="${laser_link} ${laser_link} ${laser_link}"/>
      		</geometry>
      	</collision>
      	<inertial>
      		<mass value="0.5"/>
      		<origin xyz="0 0 0" rpy=" 0 0 0"/>
	      	<inertia ixx="1e-6" ixy="0.0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
     	</inertial>
    	<visual >
      		<origin xyz="0 0 0" rpy=" 0 0 0"/>
      		<geometry>
        		<box size="${laser_link} ${laser_link} ${laser_link}"/>
      		</geometry>
    	</visual>
      </link>




  
  <joint name="left_wheel_base" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="-0.2 0.15 ${(base_link_height/2.0)-0.05+(wheel_radius-0.025)}" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1" />
  </joint>

  <joint name="right_wheel_base" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="-0.2 -0.2 ${(base_link_height/2.0)-0.05+(wheel_radius-0.025)}" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1" />
  </joint>

  <joint name="caster_base" type="fixed">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <origin xyz="0.2 0 ${ (((base_link_height/2.0)+(wheel_radius-0.025))-(base_link_height/2))/2 }" />
    <axis xyz="0 0 1" />
  </joint>

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz=" 0.275 0 0.18" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>
  
  <joint name="laser_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz=" 0.205 0 0.23" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="laser_link"/>
  </joint>


  <!--gazebo plugin-->

  <!-- camera -->
  <gazebo reference="camera_link">
    <sensor type="camera" name="camera1">
      <update_rate>50.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>800</width>
          <height>800</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <!-- Noise is sampled independently per pixel on each frame.
               That pixel's noise value is added to each of its color
               channels, which at that point lie in the range [0,1]. -->
          <mean>0.0</mean>
          <stddev>0.007</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>0.0</updateRate>
        <cameraName>rrbot/camera1</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera_link</frameName>
        <hackBaseline>0.07</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo>
  
  <!-- hokuyo laser-->
	<gazebo reference="laser_link">
		<sensor type="ray" name="head_hokuyo_sensor">
		    <pose>0 0 0 0 0 0</pose>
		    <visualize>true</visualize>
		    <update_rate>40</update_rate>
		    <ray>
		        <scan>
		            <horizontal>
		                <samples>720</samples>
		                <resolution>1</resolution>
		                <min_angle>-1.570796</min_angle>
		                <max_angle>1.570796</max_angle>
		            </horizontal>
		        </scan>
		        <range>
		            <min>0.20</min>
		            <max>10.0</max>
		            <resolution>0.02</resolution>
		        </range>
		        <noise>
		            <type>gaussian</type>
		            <!-- Noise parameters based on published spec for Hokuyo laser
		                 achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
		                 stddev of 0.01m will put 99.7% of samples within 0.03m of the true
		                 reading. -->
		            <mean>0.0</mean>
		            <stddev>0.01</stddev>
		        </noise>
		    </ray>
		    <plugin name="lidar_controller" filename="libgazebo_ros_laser.so">
		        <ros>
		            <namespace>distance</namespace>
		            <remapping>~/out:=lidar</remapping>
		        </ros>
		        <output_type>sensor_msgs/LaserScan</output_type>
		        <radiation_type>infrared</radiation_type>
		        <topicName>/laser</topicName>
		        <frameName>laser_link</frameName>
		    </plugin>
		</sensor>
	</gazebo>
  


  <gazebo reference="left_wheel">
    <material>green</material>
    <mu1>1500</mu1>
    <mu2>1500</mu2>
    <selfCollide>true</selfCollide>
  </gazebo>

  <gazebo reference="right_wheel">
    <material>green</material>
    <mu1>1500</mu1>
    <mu2>1500</mu2>
    <selfCollide>true</selfCollide>
  </gazebo>

  <!-- diff_drive -->
  <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>60</updateRate>
            <legacyMode>false</legacyMode>
            <leftJoint>left_wheel_base</leftJoint>
            <rightJoint>right_wheel_base</rightJoint>
            <wheelSeparation>0.35</wheelSeparation>
            <wheelDiameter>0.16</wheelDiameter>
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <robotBaseFrame>base_link</robotBaseFrame>
            <publishWheelTF>false</publishWheelTF>
            <publishWheelJointState>false</publishWheelJointState>
            <rosDebugLevel>na</rosDebugLevel>
            <wheelAcceleration>1</wheelAcceleration>
            <wheelTorque>50</wheelTorque>
            <odometrySource>1</odometrySource>
            <publishOdomTF>true</publishOdomTF>
            <publishTf>1</publishTf>
        </plugin>
    </gazebo> 



</robot>
